### ISSUE TITLE
Not possible to omit service worker scope

### ISSUE THREAD

**Issue by bdekok** [Notificare/notificare-push-lib-html5#1]
First of all hello! :) 

I encountered an issue where notificare wasn't working in our project. I found it this was because of the serviceWorkerScope that has to be set within the config.json. I had set it to `./` but encountered the exact situation that is described in the mdn documentation concerning the service worker scope:
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register#Examples

Right now i've solved it for us by removing the scope from the minified `notificare.min.js`, however it would be nice to have a better solution for this in the future (without me having to change minified code). Also would it be possible to also have the unminified source of the core `notificare.min.js` on github plus build?

**Comment by jjonthemix** [comment]
Hi bdekok, 

We will include this change in the next minor release. We will make it possible for developers to not include a scope at all in config.json. 

We will not publish the source code tho as this was something decided internally when we released v2. This is just the first step towards a fully managed SDK as in the future we will probably serve this over a CDN. Keep an eye on a 2.0.4 release probably by the end of the day, I'll confirm it anyway when it's done. 

I also take this opportunity to remind you to contact us via support@notifica.re for future communications. This allows us to provide faster replies and have a centralized placed where whole our team can step in if needed. Thank you.

**Comment by bdekok** [comment]
Ok, thank you for the quick response and fix.

I understand your (business) decision upon the source code. I'm not sure if serving over a CDN will work smoothly as the service worker still needs to be registered on the domain serving it.

**Comment by jjonthemix** [comment]
The idea is to let you implement your service worker (progressive apps can also use it for caching not only notifications) and simply use importScripts() to import our CDN file. 

Anyway we will release this fix soon so keep an eye on that new tag. I'll close this comment for now and please contact us via email. Thank you.
